name: Deploy Node.js Azure Function App

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Run Azure Functions Build (if any)
        run: echo "No build step for JS - skipping"

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: YOUR_FUNCTION_APP_NAME         # 👈 from Azure
          package: .                               # 👈 deploy from root
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
